"""changed Profile

Revision ID: ea556c0bcda7
Revises: c0a7da90fc34
Create Date: 2026-02-28 10:33:36.015702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea556c0bcda7'
down_revision: Union[str, Sequence[str], None] = 'c0a7da90fc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.Enum('DEFAULT', 'DETAILED', name='modeenum'), server_default=sa.text("'default'"), nullable=False))
        batch_op.drop_column('permission')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.VARCHAR(length=7), server_default=sa.text("'default'"), nullable=False))
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
